name: RutheniumCore
version: '${project.version}'
main: me.silkyfalcon.rutheniumcore.RutheniumCore
api-version: 1.16
authors: [ SilkyFalcon, Karcsi ]
website: github.com/silkyfalcon
commands:
  switcherball:
    description: Switcherball command
  rutheniumcore:
    description: Main Command
  carrow:
  timer:
